// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arvzaptlytpcqugegeyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFydnphcHRseXRwY3F1Z2VnZXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDY5MjAsImV4cCI6MjA3MTM4MjkyMH0.icoE8N-p-PzAk-ckaH0KocCZkm1SuMogPZIDGS7QLHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});